name: Test validity of json
on: [push, pull_request]

jobs:
  testjson:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: try all json files to see if they parse as valid
        run: find ${{ github.workspace }} -name '*.json' -print0 | xargs -t -0 -I{} bash -c "cat {} | python -mjson.tool"
